// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package shopify

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// Cli_MetaobjectDefinition includes the GraphQL fields of MetaobjectDefinition requested by the fragment Cli_MetaobjectDefinition.
// The GraphQL type's documentation follows.
//
// Provides the definition of a generic object structure composed of metafields.
type Cli_MetaobjectDefinition struct {
	// Access configuration for the metaobject definition.
	Access Cli_MetaobjectDefinitionAccessMetaobjectAccess `json:"access"`
	// The capabilities of the metaobject definition.
	Capabilities Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities `json:"capabilities"`
	// The administrative description.
	Description string `json:"description"`
	// The key of a field to reference as the display name for each object.
	DisplayNameKey string `json:"displayNameKey"`
	// The fields defined for this object type.
	FieldDefinitions []Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition `json:"fieldDefinitions"`
	// A globally-unique ID.
	Id string `json:"id"`
	// The human-readable name.
	Name string `json:"name"`
	// The type of the object definition. Defines the namespace of associated metafields.
	Type string `json:"type"`
}

// GetAccess returns Cli_MetaobjectDefinition.Access, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinition) GetAccess() Cli_MetaobjectDefinitionAccessMetaobjectAccess {
	return v.Access
}

// GetCapabilities returns Cli_MetaobjectDefinition.Capabilities, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinition) GetCapabilities() Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities {
	return v.Capabilities
}

// GetDescription returns Cli_MetaobjectDefinition.Description, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinition) GetDescription() string { return v.Description }

// GetDisplayNameKey returns Cli_MetaobjectDefinition.DisplayNameKey, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinition) GetDisplayNameKey() string { return v.DisplayNameKey }

// GetFieldDefinitions returns Cli_MetaobjectDefinition.FieldDefinitions, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinition) GetFieldDefinitions() []Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition {
	return v.FieldDefinitions
}

// GetId returns Cli_MetaobjectDefinition.Id, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinition) GetId() string { return v.Id }

// GetName returns Cli_MetaobjectDefinition.Name, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinition) GetName() string { return v.Name }

// GetType returns Cli_MetaobjectDefinition.Type, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinition) GetType() string { return v.Type }

// Cli_MetaobjectDefinitionAccessMetaobjectAccess includes the requested fields of the GraphQL type MetaobjectAccess.
// The GraphQL type's documentation follows.
//
// Access permissions for the definition's metaobjects.
type Cli_MetaobjectDefinitionAccessMetaobjectAccess struct {
	// The access permitted on the Admin API.
	Admin MetaobjectAdminAccess `json:"admin"`
	// The access permitted on the Storefront API.
	Storefront MetaobjectStorefrontAccess `json:"storefront"`
}

// GetAdmin returns Cli_MetaobjectDefinitionAccessMetaobjectAccess.Admin, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionAccessMetaobjectAccess) GetAdmin() MetaobjectAdminAccess {
	return v.Admin
}

// GetStorefront returns Cli_MetaobjectDefinitionAccessMetaobjectAccess.Storefront, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionAccessMetaobjectAccess) GetStorefront() MetaobjectStorefrontAccess {
	return v.Storefront
}

// Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities includes the requested fields of the GraphQL type MetaobjectCapabilities.
// The GraphQL type's documentation follows.
//
// Provides the capabilities of a metaobject definition.
type Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities struct {
	// Indicates whether a metaobject definition can be displayed as a page on the Online Store.
	OnlineStore Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStore `json:"onlineStore"`
	// Indicate whether a metaobject definition is publishable.
	Publishable Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesPublishable `json:"publishable"`
	// Indicate whether a metaobject definition is renderable and exposes SEO data.
	Renderable Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderable `json:"renderable"`
	// Indicate whether a metaobject definition is translatable.
	Translatable Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesTranslatable `json:"translatable"`
}

// GetOnlineStore returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities.OnlineStore, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities) GetOnlineStore() Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStore {
	return v.OnlineStore
}

// GetPublishable returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities.Publishable, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities) GetPublishable() Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesPublishable {
	return v.Publishable
}

// GetRenderable returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities.Renderable, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities) GetRenderable() Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderable {
	return v.Renderable
}

// GetTranslatable returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities.Translatable, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilities) GetTranslatable() Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesTranslatable {
	return v.Translatable
}

// Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStore includes the requested fields of the GraphQL type MetaobjectCapabilitiesOnlineStore.
// The GraphQL type's documentation follows.
//
// The Online Store capability of a metaobject definition.
type Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStore struct {
	// The data associated with the Online Store capability.
	Data Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStoreDataMetaobjectCapabilityDefinitionDataOnlineStore `json:"data"`
	// Indicates if the capability is enabled.
	Enabled bool `json:"enabled"`
}

// GetData returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStore.Data, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStore) GetData() Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStoreDataMetaobjectCapabilityDefinitionDataOnlineStore {
	return v.Data
}

// GetEnabled returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStore.Enabled, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStore) GetEnabled() bool {
	return v.Enabled
}

// Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStoreDataMetaobjectCapabilityDefinitionDataOnlineStore includes the requested fields of the GraphQL type MetaobjectCapabilityDefinitionDataOnlineStore.
// The GraphQL type's documentation follows.
//
// The Online Store capability data for the metaobject definition.
type Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStoreDataMetaobjectCapabilityDefinitionDataOnlineStore struct {
	// Flag indicating if a sufficient number of redirects are available to redirect all published entries.
	CanCreateRedirects bool `json:"canCreateRedirects"`
	// The URL handle for accessing pages of this metaobject type in the Online Store.
	UrlHandle string `json:"urlHandle"`
}

// GetCanCreateRedirects returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStoreDataMetaobjectCapabilityDefinitionDataOnlineStore.CanCreateRedirects, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStoreDataMetaobjectCapabilityDefinitionDataOnlineStore) GetCanCreateRedirects() bool {
	return v.CanCreateRedirects
}

// GetUrlHandle returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStoreDataMetaobjectCapabilityDefinitionDataOnlineStore.UrlHandle, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesOnlineStoreDataMetaobjectCapabilityDefinitionDataOnlineStore) GetUrlHandle() string {
	return v.UrlHandle
}

// Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesPublishable includes the requested fields of the GraphQL type MetaobjectCapabilitiesPublishable.
// The GraphQL type's documentation follows.
//
// The publishable capability of a metaobject definition.
type Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesPublishable struct {
	// Indicates if the capability is enabled.
	Enabled bool `json:"enabled"`
}

// GetEnabled returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesPublishable.Enabled, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesPublishable) GetEnabled() bool {
	return v.Enabled
}

// Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderable includes the requested fields of the GraphQL type MetaobjectCapabilitiesRenderable.
// The GraphQL type's documentation follows.
//
// The renderable capability of a metaobject definition.
type Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderable struct {
	// Indicates if the capability is enabled.
	Enabled bool `json:"enabled"`
	// The data associated with the renderable capability.
	Data Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderableDataMetaobjectCapabilityDefinitionDataRenderable `json:"data"`
}

// GetEnabled returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderable.Enabled, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderable) GetEnabled() bool {
	return v.Enabled
}

// GetData returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderable.Data, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderable) GetData() Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderableDataMetaobjectCapabilityDefinitionDataRenderable {
	return v.Data
}

// Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderableDataMetaobjectCapabilityDefinitionDataRenderable includes the requested fields of the GraphQL type MetaobjectCapabilityDefinitionDataRenderable.
// The GraphQL type's documentation follows.
//
// The renderable capability data for the metaobject definition.
type Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderableDataMetaobjectCapabilityDefinitionDataRenderable struct {
	// The metaobject field used as an alias for the SEO page description.
	MetaDescriptionKey string `json:"metaDescriptionKey"`
	// The metaobject field used as an alias for the SEO page title.
	MetaTitleKey string `json:"metaTitleKey"`
}

// GetMetaDescriptionKey returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderableDataMetaobjectCapabilityDefinitionDataRenderable.MetaDescriptionKey, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderableDataMetaobjectCapabilityDefinitionDataRenderable) GetMetaDescriptionKey() string {
	return v.MetaDescriptionKey
}

// GetMetaTitleKey returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderableDataMetaobjectCapabilityDefinitionDataRenderable.MetaTitleKey, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesRenderableDataMetaobjectCapabilityDefinitionDataRenderable) GetMetaTitleKey() string {
	return v.MetaTitleKey
}

// Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesTranslatable includes the requested fields of the GraphQL type MetaobjectCapabilitiesTranslatable.
// The GraphQL type's documentation follows.
//
// The translatable capability of a metaobject definition.
type Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesTranslatable struct {
	// Indicates if the capability is enabled.
	Enabled bool `json:"enabled"`
}

// GetEnabled returns Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesTranslatable.Enabled, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionCapabilitiesMetaobjectCapabilitiesTranslatable) GetEnabled() bool {
	return v.Enabled
}

// Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition includes the requested fields of the GraphQL type MetaobjectFieldDefinition.
// The GraphQL type's documentation follows.
//
// Defines a field for a MetaobjectDefinition with properties
// such as the field's data type and validations.
type Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition struct {
	// The administrative description.
	Description string `json:"description"`
	// A key name used to identify the field within the metaobject composition.
	Key string `json:"key"`
	// The human-readable name.
	Name string `json:"name"`
	// Required status of the field within the metaobject composition.
	Required bool `json:"required"`
	// The type of data that the field stores.
	Type Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionTypeMetafieldDefinitionType `json:"type"`
	// A list of [validation options](https://shopify.dev/apps/metafields/definitions/validation) for
	// the field. For example, a field with the type `date` can set a minimum date requirement.
	Validations []Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionValidationsMetafieldDefinitionValidation `json:"validations"`
}

// GetDescription returns Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition.Description, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition) GetDescription() string {
	return v.Description
}

// GetKey returns Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition.Key, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition) GetKey() string {
	return v.Key
}

// GetName returns Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition.Name, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition) GetName() string {
	return v.Name
}

// GetRequired returns Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition.Required, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition) GetRequired() bool {
	return v.Required
}

// GetType returns Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition.Type, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition) GetType() Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionTypeMetafieldDefinitionType {
	return v.Type
}

// GetValidations returns Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition.Validations, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinition) GetValidations() []Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionValidationsMetafieldDefinitionValidation {
	return v.Validations
}

// Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionTypeMetafieldDefinitionType includes the requested fields of the GraphQL type MetafieldDefinitionType.
// The GraphQL type's documentation follows.
//
// A metafield definition type provides basic foundation and validation for a metafield.
type Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionTypeMetafieldDefinitionType struct {
	// The category associated with the metafield definition type.
	Category string `json:"category"`
	// The name of the type for the metafield definition.
	// See the list of [supported types](https://shopify.dev/apps/metafields/types).
	Name string `json:"name"`
}

// GetCategory returns Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionTypeMetafieldDefinitionType.Category, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionTypeMetafieldDefinitionType) GetCategory() string {
	return v.Category
}

// GetName returns Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionTypeMetafieldDefinitionType.Name, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionTypeMetafieldDefinitionType) GetName() string {
	return v.Name
}

// Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionValidationsMetafieldDefinitionValidation includes the requested fields of the GraphQL type MetafieldDefinitionValidation.
// The GraphQL type's documentation follows.
//
// A configured metafield definition validation.
//
// For example, for a metafield definition of `number_integer` type, you can set a validation with the name `max`
// and a value of `15`. This validation will ensure that the value of the metafield is a number less than or equal to 15.
//
// Refer to the [list of supported validations](https://shopify.dev/api/admin/graphql/reference/common-objects/metafieldDefinitionTypes#examples-Fetch_all_metafield_definition_types).
type Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionValidationsMetafieldDefinitionValidation struct {
	// The validation name.
	Name string `json:"name"`
	// The validation value.
	Value string `json:"value"`
}

// GetName returns Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionValidationsMetafieldDefinitionValidation.Name, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionValidationsMetafieldDefinitionValidation) GetName() string {
	return v.Name
}

// GetValue returns Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionValidationsMetafieldDefinitionValidation.Value, and is useful for accessing the field via an interface.
func (v *Cli_MetaobjectDefinitionFieldDefinitionsMetaobjectFieldDefinitionValidationsMetafieldDefinitionValidation) GetValue() string {
	return v.Value
}

// GetMetaobjectDefinitionByTypeResponse is returned by GetMetaobjectDefinitionByType on success.
type GetMetaobjectDefinitionByTypeResponse struct {
	// Finds a metaobject definition by type.
	MetaobjectDefinitionByType Cli_MetaobjectDefinition `json:"metaobjectDefinitionByType"`
}

// GetMetaobjectDefinitionByType returns GetMetaobjectDefinitionByTypeResponse.MetaobjectDefinitionByType, and is useful for accessing the field via an interface.
func (v *GetMetaobjectDefinitionByTypeResponse) GetMetaobjectDefinitionByType() Cli_MetaobjectDefinition {
	return v.MetaobjectDefinitionByType
}

// ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnection includes the requested fields of the GraphQL type MetaobjectDefinitionConnection.
// The GraphQL type's documentation follows.
//
// An auto-generated type for paginating through multiple MetaobjectDefinitions.
type ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnection struct {
	// A list of nodes that are contained in MetaobjectDefinitionEdge. You can fetch data about an individual node, or you can follow the edges to fetch data about a collection of related nodes. At each node, you specify the fields that you want to retrieve.
	Nodes []Cli_MetaobjectDefinition `json:"nodes"`
	// An object that’s used to retrieve [cursor information](https://shopify.dev/api/usage/pagination-graphql) about the current page.
	PageInfo ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnectionPageInfo `json:"pageInfo"`
}

// GetNodes returns ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnection) GetNodes() []Cli_MetaobjectDefinition {
	return v.Nodes
}

// GetPageInfo returns ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnection) GetPageInfo() ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnectionPageInfo {
	return v.PageInfo
}

// ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
// The GraphQL type's documentation follows.
//
// Returns information about pagination in a connection, in accordance with the
// [Relay specification](https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo).
// For more information, please read our [GraphQL Pagination Usage Guide](https://shopify.dev/api/usage/pagination-graphql).
type ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnectionPageInfo struct {
	// Whether there are more pages to fetch following the current page.
	HasNextPage bool `json:"hasNextPage"`
	// The cursor corresponding to the last node in edges.
	EndCursor string `json:"endCursor"`
}

// GetHasNextPage returns ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnectionPageInfo) GetEndCursor() string {
	return v.EndCursor
}

// ListMetaobjectDefinitionsResponse is returned by ListMetaobjectDefinitions on success.
type ListMetaobjectDefinitionsResponse struct {
	// All metaobject definitions.
	MetaobjectDefinitions ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnection `json:"metaobjectDefinitions"`
}

// GetMetaobjectDefinitions returns ListMetaobjectDefinitionsResponse.MetaobjectDefinitions, and is useful for accessing the field via an interface.
func (v *ListMetaobjectDefinitionsResponse) GetMetaobjectDefinitions() ListMetaobjectDefinitionsMetaobjectDefinitionsMetaobjectDefinitionConnection {
	return v.MetaobjectDefinitions
}

// Metaobject access permissions for the Admin API. When the metaobject is app-owned, the owning app always has
// full access.
type MetaobjectAdminAccess string

const (
	// The merchant and other apps have no access.
	MetaobjectAdminAccessPrivate MetaobjectAdminAccess = "PRIVATE"
	// The merchant has read-only access. No other apps have access.
	MetaobjectAdminAccessMerchantRead MetaobjectAdminAccess = "MERCHANT_READ"
	// The merchant has read and write access. No other apps have access.
	MetaobjectAdminAccessMerchantReadWrite MetaobjectAdminAccess = "MERCHANT_READ_WRITE"
	// The merchant and other apps have read-only access.
	MetaobjectAdminAccessPublicRead MetaobjectAdminAccess = "PUBLIC_READ"
	// The merchant and other apps have read and write access.
	MetaobjectAdminAccessPublicReadWrite MetaobjectAdminAccess = "PUBLIC_READ_WRITE"
)

var AllMetaobjectAdminAccess = []MetaobjectAdminAccess{
	MetaobjectAdminAccessPrivate,
	MetaobjectAdminAccessMerchantRead,
	MetaobjectAdminAccessMerchantReadWrite,
	MetaobjectAdminAccessPublicRead,
	MetaobjectAdminAccessPublicReadWrite,
}

// Metaobject access permissions for the Storefront API.
type MetaobjectStorefrontAccess string

const (
	// No access.
	MetaobjectStorefrontAccessNone MetaobjectStorefrontAccess = "NONE"
	// Read-only access.
	MetaobjectStorefrontAccessPublicRead MetaobjectStorefrontAccess = "PUBLIC_READ"
)

var AllMetaobjectStorefrontAccess = []MetaobjectStorefrontAccess{
	MetaobjectStorefrontAccessNone,
	MetaobjectStorefrontAccessPublicRead,
}

// __GetMetaobjectDefinitionByTypeInput is used internally by genqlient
type __GetMetaobjectDefinitionByTypeInput struct {
	DefType string `json:"defType"`
}

// GetDefType returns __GetMetaobjectDefinitionByTypeInput.DefType, and is useful for accessing the field via an interface.
func (v *__GetMetaobjectDefinitionByTypeInput) GetDefType() string { return v.DefType }

// __ListMetaobjectDefinitionsInput is used internally by genqlient
type __ListMetaobjectDefinitionsInput struct {
	First int    `json:"first"`
	After string `json:"after,omitempty"`
}

// GetFirst returns __ListMetaobjectDefinitionsInput.First, and is useful for accessing the field via an interface.
func (v *__ListMetaobjectDefinitionsInput) GetFirst() int { return v.First }

// GetAfter returns __ListMetaobjectDefinitionsInput.After, and is useful for accessing the field via an interface.
func (v *__ListMetaobjectDefinitionsInput) GetAfter() string { return v.After }

// The query executed by GetMetaobjectDefinitionByType.
const GetMetaobjectDefinitionByType_Operation = `
query GetMetaobjectDefinitionByType ($defType: String!) {
	metaobjectDefinitionByType(type: $defType) {
		... Cli_MetaobjectDefinition
	}
}
fragment Cli_MetaobjectDefinition on MetaobjectDefinition {
	access {
		admin
		storefront
	}
	capabilities {
		onlineStore {
			data {
				canCreateRedirects
				urlHandle
			}
			enabled
		}
		publishable {
			enabled
		}
		renderable {
			enabled
			data {
				metaDescriptionKey
				metaTitleKey
			}
		}
		translatable {
			enabled
		}
	}
	description
	displayNameKey
	fieldDefinitions {
		description
		key
		name
		required
		type {
			category
			name
		}
		validations {
			name
			value
		}
	}
	id
	name
	type
}
`

func GetMetaobjectDefinitionByType(
	ctx_ context.Context,
	client_ graphql.Client,
	defType string,
) (data_ *GetMetaobjectDefinitionByTypeResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetMetaobjectDefinitionByType",
		Query:  GetMetaobjectDefinitionByType_Operation,
		Variables: &__GetMetaobjectDefinitionByTypeInput{
			DefType: defType,
		},
	}

	data_ = &GetMetaobjectDefinitionByTypeResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListMetaobjectDefinitions.
const ListMetaobjectDefinitions_Operation = `
query ListMetaobjectDefinitions ($first: Int!, $after: String) {
	metaobjectDefinitions(first: $first, after: $after) {
		nodes {
			... Cli_MetaobjectDefinition
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
fragment Cli_MetaobjectDefinition on MetaobjectDefinition {
	access {
		admin
		storefront
	}
	capabilities {
		onlineStore {
			data {
				canCreateRedirects
				urlHandle
			}
			enabled
		}
		publishable {
			enabled
		}
		renderable {
			enabled
			data {
				metaDescriptionKey
				metaTitleKey
			}
		}
		translatable {
			enabled
		}
	}
	description
	displayNameKey
	fieldDefinitions {
		description
		key
		name
		required
		type {
			category
			name
		}
		validations {
			name
			value
		}
	}
	id
	name
	type
}
`

func ListMetaobjectDefinitions(
	ctx_ context.Context,
	client_ graphql.Client,
	first int,
	after string,
) (data_ *ListMetaobjectDefinitionsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListMetaobjectDefinitions",
		Query:  ListMetaobjectDefinitions_Operation,
		Variables: &__ListMetaobjectDefinitionsInput{
			First: first,
			After: after,
		},
	}

	data_ = &ListMetaobjectDefinitionsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
